AWSTemplateFormatVersion: '2010-09-09'
Description: NoorSecure IAM Stack - Least privilege roles for Lambda & AWS Config

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NoorSecureLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  ConfigServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NoorSecureAWSConfigRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ConfigWriteToS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketAcl
                Resource: "*"

Outputs:
  LambdaRoleArn:
    Value: !GetAtt LambdaExecutionRole.Arn
    Description: Lambda IAM Role ARN

  ConfigRoleArn:
    Value: !GetAtt ConfigServiceRole.Arn
    Description: AWS Config Role ARN

