AWSTemplateFormatVersion: '2010-09-09'
Description: NoorSecure Security Stack – GuardDuty, CloudTrail, AWS Config, secure S3 logging

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: noorsecure-logs-429128462098-us-east-1

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${LogBucket}
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${LogBucket}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: NoorSecureTrail
      S3BucketName: !Ref LogBucket
      IsLogging: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true

  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: ConfigRecorder
      RoleARN: arn:aws:iam::429128462098:role/NoorSecureAWSConfigRole
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  DeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName: !Ref LogBucket
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: One_Hour

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true

