AWSTemplateFormatVersion: '2010-09-09'
Description: snsecure-pro-logging - CloudTrail + secure S3 + CloudWatch Logs integration

Parameters:
  ProjectTag:
    Type: String
    Default: snsecure-pro

Resources:

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: snsecure-pro-logs-429128462098
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  LogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: arn:aws:s3:::snsecure-pro-logs-429128462098

          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: arn:aws:s3:::snsecure-pro-logs-429128462098/AWSLogs/429128462098/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/cloudtrail/${ProjectTag}-trail"
      RetentionInDays: 90

  TrailRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectTag}-trail-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudWatchLogDelivery
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogStream
                Resource: "*"

  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub "${ProjectTag}-trail"
      S3BucketName: snsecure-pro-logs-429128462098
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      IsLogging: true
      CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt TrailRole.Arn

Outputs:
  LogBucketName:
    Description: S3 bucket used for CloudTrail logs
    Value: !Ref LogBucket

  TrailName:
    Description: CloudTrail trail name
    Value: !Ref Trail

