AWSTemplateFormatVersion: '2010-09-09'
Description: snsecure-pro-security - GuardDuty and Security Hub monitoring

Parameters:
  ProjectTag:
    Type: String
    Default: snsecure-pro

Resources:

  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: SIX_HOURS
      Tags:
        - Key: Project
          Value: !Ref ProjectTag

  SecurityHub:
    Type: AWS::SecurityHub::Hub
    Properties:
      Tags:
        Project: !Ref ProjectTag

Outputs:
  GuardDutyDetectorId:
    Description: GuardDuty detector ID
    Value: !Ref GuardDutyDetector

  SecurityHubArn:
    Description: Security Hub ARN
    Value: !Ref SecurityHub

